apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: antifraude-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/criptomoney0101/antifraude-app.git
    targetRevision: HEAD
    path: helm/antifraude
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true
